name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - MoveToAzureFunctions
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - MoveToAzureFunctions

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Define Build variables
        working-directory: '/home/runner/work/ChargeAndChange/ChargeAndChange'
        run: |
          ls -la
          echo workspace is ${{ github.workspace }}
          echo $GITHUB_RUN_NUMBER >GITHUB_RUN_NUMBER
          echo $GITHUB_RUN_ID >GITHUB_RUN_ID
          echo $GITHUB_SHA >GITHUB_SHA
          echo $(cat GITHUB_RUN_NUMBER)
          echo $(cat GITHUB_RUN_ID)
          echo $(cat GITHUB_SHA)
          echo $(cat BlazorClient/AppVersionInfo.cs)
         
          echo format ('cat BlazorClient/AppVersionInfo.cs | sed ''s/_buildNumber = ""/_buildNumber = "{0}"/'' | sed ''s/_buildId = ""/_buildId = "{1}"/'' | sed ''s/_gitHash = ""/_gitHash = "{2}"/'' >temp.cs', $GITHUB_RUN_NUMBER,$GITHUB_RUN_ID,$GITHUB_SHA) >command 
          echo $(cat command)
          echo $($cat command))
          cat temp.cs >BlazorClient/AppVersionInfo.cs
         
      - uses: pCYSl5EDgo/cat@master
        id: dump
        with:
          path: /home/runner/work/ChargeAndChange/ChargeAndChange/BlazorClient/AppVersionInfo.cs

      - run: echo $TEXT
        env:
          TEXT: ${{ steps.dump.outputs.text }}
        
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_DESERT_02E31401E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "BlazorClient" # App source code path
          api_location: "WebApi" # Api source code path - optional
          output_location: "wwwroot" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_DESERT_02E31401E }}
          action: "close"
